# .github/dependabot.yml

version: 2
updates:

  # Keep dependencies for GitHub Actions updated daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[GH Actions]"
    labels:
      - "dependency"
      - "github-actions"

  # NPM for JavaScript/TypeScript projects
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[npm]"
    labels:
      - "dependency"
      - "npm"

  # Maven for Java projects
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[maven]"
    labels:
      - "dependency"
      - "maven"

  # Pip for Python projects
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[pip]"
    labels:
      - "dependency"
      - "pip"

  # Gem for Ruby projects
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[bundler]"
    labels:
      - "dependency"
      - "ruby"

  # Gradle for Java/Kotlin projects
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gradle]"
    labels:
      - "dependency"
      - "gradle"

  # NuGet for .NET projects
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget]"
    labels:
      - "dependency"
      - "nuget"

  # Composer for PHP projects
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[composer]"
    labels:
      - "dependency"
      - "composer"

  # Cargo for Rust projects
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[cargo]"
    labels:
      - "dependency"
      - "cargo"

  # Go modules for Go projects
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gomod]"
    labels:
      - "dependency"
      - "go"

  # Yarn for JavaScript/TypeScript projects (if you're not using npm)
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[yarn]"
    labels:
      - "dependency"
      - "yarn"

  # Docker for container images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker]"
    labels:
      - "dependency"
      - "docker"

  # Elixir's Mix for Elixir projects
  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[hex]"
    labels:
      - "dependency"
      - "elixir"

  # Terraform for infrastructure as code
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[terraform]"
    labels:
      - "dependency"
      - "terraform"

  # Sbt for Scala projects
  - package-ecosystem: "sbt"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[sbt]"
    labels:
      - "dependency"
      - "scala"

  # Swift's Package Manager for Swift projects
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[swift]"
    labels:
      - "dependency"
      - "swift"
      
  # Helm for Kubernetes applications
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[helm]"
    labels:
      - "dependency"
      - "helm"

  
  # General PR settings
  - open-pull-requests-limit: 100
      target-branch: "main"
      reviewers:
          - "username1"
          - "username2"
      assignees:
          - "username1"
      milestone: 1
      
        # Security updates are given a high priority
      versioning-strategy: "increase"
      allow:
        - dependency-name: "*"
          dependency-type: "direct"
